image: docker:20.10.16   # has docker CLI

stages:
  - checkout
  - build
  - deploy

variables:
  PROJECT_ID: "nimble-poet-470622-s8"
  REGION: "us-central1"
  REPO: "llmops-repo"
  REGISTRY: "us-central1-docker.pkg.dev"
  CLUSTER: "llmops"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""   # required for DinD

checkout_code:
  stage: checkout
  script:
    - echo "Code Checked out.."

build_docker_image:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    # install gcloud SDK inside docker image
    - apk add --no-cache python3 py3-pip curl bash git openjdk11
    - curl -sSL https://sdk.cloud.google.com | bash
    - exec -l $SHELL
    - echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud auth configure-docker $REGISTRY --quiet
  script:
    - docker build -t $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest .
    - docker push $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest

deploy_to_gke:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
  script:
    - gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID
    - kubectl apply -f kubernetes-deployment.yaml
